name: Deploy Hokage Terminal to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the workflow every time you push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-node-version: 18
          cache: 'yarn' # Change to 'npm' if you use package-lock.json instead of yarn.lock

      - name: Setup GitHub Pages Metadata
        uses: actions/configure-pages@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile # Change to 'npm ci' if using npm

      - name: Compile and Export Static HTML
        run: yarn build # Runs next build and exports to /out

      - name: Upload Static Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages Live Engine
        id: deployment
        uses: actions/deploy-pages@v4